---
- hosts: all
  remote_user: vagrant
  sudo: yes

  vars_files:
    - vars/redis.yml
    - vars/mysql.yml
    - vars/postgresql.yml

  roles:
    - ANXS.mysql
    - ANXS.postgresql
    - ANXS.utilities
    - DavidWittman.redis
