---
- hosts: all
  remote_user: vagrant
  sudo: yes

  vars_files:
    - vars/rbenv.yml

  roles:
    - ANXS.utilities
    - ANXS.nodejs
    - pablocrivella.rbenv
    - role: pablocrivella.heroku-toolbelt
      heroku_toolbelt_users:
        - vagrant

  post_tasks:
    - include: tasks/install_gem_dependencies.yml
